### ISSUE TITLE
JDK8 里Nimbus -XX:MaxTenuringThreshold 的最大值是15，默认配置里的是20

### ISSUE THREAD

**Issue by lispking** [alibaba/jstorm#109]
#84 
https://github.com/alibaba/jstorm/blob/master/jstorm-server/src/main/resources/defaults.yaml#L40
nimbus还是有问题的

**Comment by longdafeng** [comment]
fixed in 2.1.1 

另外， 如果你用老版本， 你把gc 参数拉出来
nimbus.childopts: " -Xms4g -Xmx4g -Xmn1536m -XX:PermSize=256m  -XX:SurvivorRatio=4 -XX:MaxTenuringThreshold=15 -XX:+UseConcMarkSweepGC  -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:CMSFullGCsBeforeCompaction=5 -XX:+HeapDumpOnOutOfMemoryError  -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=100M -XX:+UseCMSCompactAtFullCollection -XX:CMSMaxAbortablePrecleanTime=5000 "

**Comment by chenatu** [comment]
2.1.1的bin版本 利用默认参数启动 jdk8启动还是报这个问题 并没有修复好。
