### ISSUE TITLE
Upgrade topology in Production

### ISSUE THREAD

**Issue by charlieyxl** [alibaba/jstorm#190]
How to upgrade topology in Production without losing service at all? Thanks!

**Comment by wuchong** [comment]
You can try this command `jstorm update_topology topology-name -jar [jarpath] -conf [confpath]`

it will upload the new topology jar , and it will be out of service for only a short time

**Comment by unsleepy22** [comment]
It's a complex topic. Depending on what you mean by 'without losing service', if you mean to update topology logic without stopping it, it's difficult to accomplish this for now. However, you can find some workaround. For example, you can make your application function configurable so that by simply updating the topology config you've also updated the function of your code. Or maybe you can  put some groovy scripts in your code and make it updatable(i.e., code as config like python). Hope this helps.

**Comment by unsleepy22** [comment]
It's kind of hot deployment, we may need some tricks to do the magic(like OSGi or pandora container in Alibaba), it may not be impossible, but it might not be our first priority currently.

**Comment by charlieyxl** [comment]
Thanks a lot!

**Comment by gavinfish** [comment]
@unsleepy22  I am also interested in this topic. In the JStorm-introduce ppt, there is a feature as 'Dynamic Expand/Reload/Restart' on page 22. But according to the conversation above, JStorm has not supported hot deployment of topology. So what does 'Dynamic Restart' mean? Can I update configuration without restarting service and how?
